#!/bin/bash
read -p "Enter Customer Account Name(CLIENTNAME-ALIAS): " CLIENT_ACCOUNT
read -p "Enter SNS TOPIC: " SNS_TOPIC
read -p "Enter Region: " REGION
read -p "Enter Priority Level: " PRIORITY

# Get a list of all ELBs in the region
ELB_NAMES=$(aws elbv2 describe-load-balancers --region $AWS_REGION --query "LoadBalancers[].LoadBalancerName" --output text)

# Iterate over each ELB name and create a CloudWatch alarm for 5xx errors
for ELB_NAME in $ELB_NAMES; do
  # Create the CloudWatch alarm
  aws cloudwatch put-metric-alarm --region $AWS_REGION --alarm-name "${CLIENT_ACCOUNT} - ${PRIORITY} - Critical Sum of 5xx errors on ${ELB_NAME}" --alarm-description "Alarm for $ELB_NAME - 5xxErrors" --metric-name HTTPCode_Target_5XX_Count --namespace AWS/ApplicationELB --statistic Sum --period 60 --threshold 1 --comparison-operator GreaterThanOrEqualToThreshold --dimensions Name=LoadBalancer,Value=$ELB_NAME --evaluation-periods 1 --alarm-actions ${SNS_TOPIC}
done


