#!/bin/bash
read -p 'Enter Priority Level' PRIORITY

# Generate ARN of LBs
aws elbv2 describe-load-balancers --region ap-southeast-1 --query "LoadBalancers[].LoadBalancerArn" --output text \
| awk '{ for (i=1; i<=NF; i++) printf "%s\n", $i }' > arnlist.txt

#Generate Target group from Arnlist
while read ARN;
do aws elbv2 describe-target-groups --query "TargetGroups[].TargetGroupArn" --load-balancer-arn ${ARN} --output text >> targetgroups.txt;
done < prod-arnlist.txt;

# Remove the string 'arn:aws:elasticloadbalancing:ap-southeast-1:xxxxxxxx:' from targetgroup txt arn
sed -i 's/arn:aws:elasticloadbalancing:ap-southeast-1:xxxxxxxx://g' targetgroups.txt
# Remove the string 'arn:aws:elasticloadbalancing:ap-southeast-1:xxxxxxxx:loadbalancer/' from the ARN list
sed -i 's/arn:aws:elasticloadbalancing:ap-southeast-1:xxxxxxxx:loadbalancer\///g' prod-arnlist.txt

paste -d '\n' stg-arnlist.txt targetgroups.txt | awk 'NF' > readfile.txt

#Create Cloudwatch alarms
while read LB; read TG;
do aws cloudwatch put-metric-alarm \
    --alarm-name "JFC-DT - $PRIORITY - Critical UnHealthyHostCount ($LB)" \
    --alarm-description "unhealthy host count is greater than 0" \
    --metric-name UnHealthyHostCount \
    --namespace AWS/ApplicationELB \
    --statistic Sum \
    --period 300 \
    --treat-missing-data notBreaching \
    --threshold 0 \
    --comparison-operator GreaterThanThreshold \
    --dimensions Name='LoadBalancer',Value=\'${LB}\' Name='TargetGroup',Value=${TG} \
    --evaluation-periods 1 \
    --alarm-actions arn:aws:sns:ap-southeast-1:xxxxxxxx:SNS-NAME \
    --unit Count \
    --region ap-southeast-1;
done < readfile.txt;