#!/bin/bash
aws ec2 describe-images \
    --region ap-southeast-1 \
    --query "Images[?CreationDate<'2023-08-01'].{ID:ImageId,Name:Name,CreationDate:CreationDate}" \
    --output text > images.txt

while read images;
do aws ec2 deregister-image --image-id $images --region ap-southeast-1;
done < images.txt